export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BOOKS_ROUTE = '/'
export const BOXES_ROUTE = '/boxes'
export const ABOUT_ROUTE = '/about'
export const CONTACTS_ROUTE = '/contacts'
export const BOOKPAGE_ROUTE = '/book'
